import './index.less';
import '../primitives/style';
import '../icon/style';
import '../button/style';
import '../form/style';
import '../text-field/style';
import '../select/style';
import '../pagination/style';
import '../table/style';
